:root{font-family:Segoe UI,Arial,sans-serif;color:#181a1d;background:#f4f5f7}*{box-sizing:border-box}body{margin:0}.wrap{max-width:980px;margin:auto;padding:16px}.top{display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap}.card{background:#fff;border:1px solid #d8dce2;border-radius:12px;padding:16px;margin-top:14px}.tabs{display:flex;gap:8px;overflow:auto;margin-top:14px}.tabs button{white-space:nowrap}.tabs button.active{background:#202226;color:white}.page{display:none}.page.active{display:block}button,input,select,textarea{font:inherit;border:1px solid #b9bec7;border-radius:8px;padding:10px}button{cursor:pointer;background:#fff}button.primary{background:#202226;color:#fff;border-color:#202226}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grow{flex:1;min-width:180px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.days{display:grid;grid-template-columns:130px 90px 1fr 1fr;gap:8px;align-items:center}.speedrow{display:grid;grid-template-columns:32px 1fr 130px 42px;gap:8px;margin:8px 0}.status{font-size:14px;color:#555}.ok{color:#166534}.bad{color:#991b1b}textarea{width:100%;min-height:130px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #e4e6e9;text-align:left;font-size:14px}@media(max-width:650px){.grid2{grid-template-columns:1fr}.days{grid-template-columns:90px 70px 1fr 1fr;font-size:13px}.speedrow{grid-template-columns:30px 1fr 110px 38px}.wrap{padding:10px}}</style></head><body><div class="wrap"><div class="top"><div><h2 style="margin:0">Hadi WiFi Router</h2><div class="status" id="summary">Loading...</div></div><div class="row"><button id="refresh">Refresh</button><button id="logout">Sign out</button></div></div>
<div class="tabs"><button data-p="hot" class="active">Hotspot</button><button data-p="sched">Schedule</button><button data-p="web">Website Rules</button><button data-p="speed">Speed</button><button data-p="dev">Devices</button></div>
<div id="hot" class="page active"><div class="card"><div class="row"><button class="primary" id="start">Start Wi-Fi</button><button id="stop">Stop Wi-Fi</button><span id="hotstatus" class="status"></span></div><div class="grid2" style="margin-top:14px"><label>Wi-Fi name<input id="ssid" class="grow" style="width:100%"></label><label>Password<input id="pass" class="grow" style="width:100%" type="password"></label></div><label class="row" style="margin-top:12px"><input type="checkbox" id="hotenabled"> Controlled Wi-Fi enabled</label><button class="primary" id="savehot" style="margin-top:12px">Save hotspot settings</button></div></div>
<div id="sched" class="page"><div class="card"><label class="row"><input type="checkbox" id="schenabled"> Enable weekly schedule</label><div class="days" id="days" style="margin-top:12px"></div><button class="primary" id="savesched" style="margin-top:14px">Save schedule</button></div></div>
<div id="web" class="page"><div class="card"><label class="row"><input type="checkbox" id="webenabled"> Enable blocking for hotspot clients</label><h4>Service profiles</h4><div class="row" id="services"></div><div class="grid2" style="margin-top:14px"><label>Custom blocked domains<textarea id="blocked"></textarea></label><label>Allowed domains<textarea id="allowed"></textarea></label></div><button class="primary" id="saveweb" style="margin-top:12px">Save website rules</button><span class="status" id="webmsg"></span></div></div>
<div id="speed" class="page"><div class="card"><label class="row"><input type="checkbox" id="speedenabled"> Enable speed control</label><div class="status">Low = 256 Kbps · Medium = 1 Mbps · Max = 5 Mbps</div><div id="speedrows" style="margin-top:10px"></div><div class="row"><button id="addspeed">Add target</button><button class="primary" id="savespeed">Save speed rules</button><span id="speedmsg" class="status"></span></div></div></div>
<div id="dev" class="page"><div class="card"><div class="row"><button id="refreshdev">Refresh devices</button><span id="devcount" class="status"></span></div><div style="overflow:auto"><table><thead><tr><th>Device</th><th>IP</th><th>MAC</th><th>State</th></tr></thead><tbody id="devbody"></tbody></table></div></div></div>
</div><script>
let state=null;const $=x=>document.getElementById(x);document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.p).classList.add('active');if(b.dataset.p==='dev')load()});
async function api(path,opt={}){const r=await fetch(path,opt);if(r.status===401){location.reload();throw new Error('signed out')}const t=await r.text();let j={};try{j=JSON.parse(t)}catch{j={message:t}}if(!r.ok)throw new Error(j.error||j.message||'Request failed');return j}
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];function addSpeed(r={Enabled:true,Domain:'',Level:'Medium'}){const d=document.createElement('div');d.className='speedrow';d.innerHTML=`<input type="checkbox" ${r.Enabled?'checked':''}><input class="dom" value="${String(r.Domain||'').replaceAll('&','&amp;').replaceAll('"','&quot;')}"><select><option>Max</option><option>Medium</option><option>Low</option></select><button>×</button>`;d.querySelector('select').value=r.Level||'Medium';d.querySelector('button').onclick=()=>d.remove();$('speedrows').appendChild(d)}
function render(s){state=s;const c=s.config;$('summary').textContent=`Hotspot: ${s.hotspot.State} · Clients: ${s.hotspot.ClientCount} · ${new Date().toLocaleTimeString()}`;$('hotstatus').textContent=`${s.hotspot.State} / ${s.hotspot.Status||''}`;$('ssid').value=c.SSID||'';$('pass').value=c.Password||'';$('hotenabled').checked=!!c.HotspotEnabled;$('schenabled').checked=!!c.ScheduleEnabled;$('webenabled').checked=!!c.WebsiteFilteringEnabled;$('blocked').value=(c.BlockedDomains||[]).join('\n');$('allowed').value=(c.AllowedDomains||[]).join('\n');$('speedenabled').checked=!!c.SpeedControlEnabled;
$('days').innerHTML='<b>Day</b><b>Target</b><b>Start</b><b>Stop</b>';(c.ScheduleRules||[]).forEach((q,i)=>{$('days').insertAdjacentHTML('beforeend',`<select class="rday"><option>${q.Day}</option>${days.filter(x=>x!==q.Day).map(x=>`<option>${x}</option>`).join('')}</select><select class="rtarget">${['Whole traffic','YouTube','TikTok','Instagram','Snapchat'].map(x=>`<option ${x===q.Target?'selected':''}>${x}</option>`).join('')}</select><input class="rstart" type="time" value="${q.Start}"><input class="rstop" type="time" value="${q.Stop}">`)});
$('services').innerHTML='';['YouTube','TikTok','Instagram','Snapchat'].forEach(x=>{const l=document.createElement('label');l.className='row';l.innerHTML=`<input type="checkbox" data-svc="${x}" ${(c.BlockedServices||[]).includes(x)?'checked':''}> ${x}`;$('services').appendChild(l)});$('speedrows').innerHTML='';(c.SpeedRules||[]).forEach(addSpeed);renderDevices(s.devices||[])}
function renderDevices(a){$('devbody').innerHTML='';a.forEach(x=>$('devbody').insertAdjacentHTML('beforeend',`<tr><td>${x.Device||''}</td><td>${x.IPAddress||''}</td><td>${x.MACAddress||''}</td><td>${x.State||''}</td></tr>`));$('devcount').textContent=`${a.length} visible device(s)`}
async function load(){try{render(await api('/api/status'))}catch(e){$('summary').textContent=e.message}}
function jsonPost(path,o){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)})}
$('refresh').onclick=load;$('refreshdev').onclick=load;$('logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};$('start').onclick=async()=>{await jsonPost('/api/hotspot/start',{SSID:$('ssid').value,Password:$('pass').value});load()};$('stop').onclick=async()=>{await api('/api/hotspot/stop',{method:'POST'});load()};
$('savehot').onclick=async()=>{await jsonPost('/api/hotspot/save',{HotspotEnabled:$('hotenabled').checked,SSID:$('ssid').value,Password:$('pass').value});load()};
$('savesched').onclick=async()=>{const rr=[...document.querySelectorAll('#days .rday')].map((x,i)=>({Enabled:true,Day:x.value,Target:document.querySelectorAll('#days .rtarget')[i].value,Start:document.querySelectorAll('#days .rstart')[i].value,Stop:document.querySelectorAll('#days .rstop')[i].value}));await jsonPost('/api/schedule',{ScheduleEnabled:$('schenabled').checked,ScheduleRules:rr});load()};
$('saveweb').onclick=async()=>{const sv=[...document.querySelectorAll('[data-svc]:checked')].map(x=>x.dataset.svc);const o={WebsiteFilteringEnabled:$('webenabled').checked,BlockedServices:sv,BlockedDomains:$('blocked').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),AllowedDomains:$('allowed').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)};const x=await jsonPost('/api/website',o);$('webmsg').textContent=x.message||'Saved';load()};
$('addspeed').onclick=()=>addSpeed();$('savespeed').onclick=async()=>{const rs=[...document.querySelectorAll('#speedrows .speedrow')].map(r=>({Enabled:r.children[0].checked,Domain:r.querySelector('.dom').value.trim(),Level:r.querySelector('select').value})).filter(x=>x.Domain);const x=await jsonPost('/api/speed',{SpeedControlEnabled:$('speedenabled').checked,SpeedRules:rs});$('speedmsg').textContent=x.message||'Saved';load()};load();setInterval(()=>{if(document.visibilityState==='visible')load()},5000);
</script></body></html>
'@

$listener=New-Object Net.HttpListener
$listener.Prefixes.Add('http://127.0.0.1:8787/')

# Remote access is bound directly to this PC's private Tailscale IPv4 address.
# This avoids Tailscale Serve/HTTPS setup prompts while the Tailscale tunnel itself
# still provides end-to-end encryption. If Tailscale is not ready at boot, exit so
# Task Scheduler can retry this service automatically.
$tsExe='C:\Program Files\Tailscale\tailscale.exe'
$tsIp=$null
if(Test-Path $tsExe){
    for($i=0;$i -lt 30 -and -not $tsIp;$i++){
        try{
            $candidate=@(& $tsExe ip -4 2>$null)|Select-Object -First 1
            if($candidate){$candidate=([string]$candidate).Trim();if($candidate -match '^100\.'){$tsIp=$candidate}}
        }catch{}
